# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ns_r_7DZolONIxyFlGnJbg811OkA1b-U
"""

def calculadora():
  while True:
    opcao = input("Escolha umas das opções: 1: soma, 2: subtração, 3: multiplicação, 4: divisão, 0: sair ")

    if (opcao == '1'):
      num1 = float(input("Digite o primeiro valor: "))
      num2 = float(input("Digite o segundo valor: "))
      resultado = num1 + num2
      print("Resultado: ", resultado)
    elif (opcao == '2'):
      num1 = float(input("Digite o primeiro valor: "))
      num2 = float(input("Digite o segundo valor: "))
      resultado = num1 - num2
      print("Resultado: ", resultado)
    elif (opcao == '3'):
      num1 = float(input("Digite o primeiro valor: "))
      num2 = float(input("Digite o segundo valor: "))
      resultado = num1 * num2
      print("Resultado: ", resultado)
    elif (opcao == '4'):
      num1 = float(input("Digite o primeiro valor: "))
      num2 = float(input("Digite o segundo valor: "))
      resultado = num1 / num2
      print("Resultado: ", resultado)
    elif (opcao == '0'):
      print("Saindo da calculadora!!")
      break

calculadora()