# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KJPJoYmMwfD8nUjmA56l290TT7PFLykn
"""

def calculadora(numero1, numero2, operacao):
  if (operacao == '+'):
    resultado = numero1 + numero2
    print(numero1, ' + ', numero2, ' = ', resultado)
  elif (operacao == '-'):
    resultado = numero1 - numero2
    print(numero1, ' - ', numero2, ' = ', resultado)
  elif (operacao == '*'):
    resultado = numero1 * numero2
    print(numero1, ' * ', numero2, ' = ', resultado)
  elif (operacao == '/'):
    resultado = numero1 / numero2
    print(numero1, ' / ', numero2, ' = ', resultado)

calculadora(1, 1, '+')
calculadora(2, 1, '-')
calculadora(3, 1, '*')
calculadora(4, 2, '/')