# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KJPJoYmMwfD8nUjmA56l290TT7PFLykn
"""

def nomeIdade():
  numeroCorreto = False
  nome = input("Digite seu nome completo: ")

  print("Digite seu ano de nascimento: ")
  while (numeroCorreto == False):
    try:
      anoNascimento = int(input())
      if (anoNascimento >= 1922) and (anoNascimento < 2022):
        numeroCorreto = True
        idade = 2022 - anoNascimento
        print(nome, ' tem ', idade, ' em 2022')
    except:
      print("Digite o ano correto")

nomeIdade()