# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hxv7V75fxGuDrek_pkb-4EWmhsMO3kYX
"""

totalAndares = 20
andar = 0

for i in range(totalAndares):
  andar = andar + 1
  if (andar == 13):
    continue
  print('Andar: ', andar)

print('-----------')
contador = 0

while (totalAndares > contador):
  print('Andar: ', totalAndares)
  totalAndares = totalAndares - 1

